name: recipe_book_flutter
description: Bored with the same old recipes? Want to try something new with the same old ingredients?
  This app contains recipes from all across the world. Make those boring ingredients delish. 
  Recommended by 27 Masterchefs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.11
  # Add any additional packages you need here

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
